server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: lvquan
    url: jdbc:mysql://localhost:3306/wali?characterEncoding=utf8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
mybatis:
  type-aliases-package: com.guigu.cloud.entity
  mapper-locations: classpath:mapper/*.xml